apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mihir-springboot
labels:
  app: mihir-springboot
  book: mihirbook
version: v1
spec:
replicas: 1
selector:
matchLabels:
app: mihir-springboot
version: v1
template:
metadata:
labels:
app: mihir-springboot
book: mihirbook
version: v1
spec:
containers:
- env:
#- name: JAVA_OPTIONS
#value: -Xmx256m -Djava.net.preferIPv4Stack=true
#- name: GREETING_BACKENDSERVICEHOST
#value: backend
image: mihirjh/mihir-springboot:1.0
imagePullPolicy: IfNotPresent
livenessProbe:
httpGet: # make an HTTP request
port: 8080 # port to use
path: /actuator/health # endpoint to hit
scheme: HTTP # or HTTPS
initialDelaySeconds: 20
periodSeconds: 5
timeoutSeconds: 1
name: mihir-springboot
ports:
- containerPort: 8080
name: http
protocol: TCP
readinessProbe:
httpGet: # make an HTTP request
port: 8080 # port to use
path: /actuator/health # endpoint to hit
scheme: HTTP # or HTTPS
initialDelaySeconds: 10
periodSeconds: 5
timeoutSeconds: 1
