apiVersion: v1
kind: Service
metadata:
  name: mihir-springboot
  labels:
    app: mihir-springboot
    book: mihirbook
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: mihir-springboot

